### ISSUE TITLE
agg: new implementation

### ISSUE THREAD

**Issue by tsuyoshicho** [tsuyoshicho/vital-codec#79]
- [ ] Hash.SipHash #75
- [ ] Crypt.Symmetric.ChaCha20 #74
- [ ] Crypt.MAC.Poly1305 #74
- [ ] Crypt.Password.scrypt #72
- [ ] Random.Liner #66
- [ ] Crypt.DRBG.Hash_DRBG #52 
- [ ] Crypt.DRBG.HMAC_DRBG #52 
- [ ] Crypt.DRBG.CTR_DBRG #52 

---

move
- [ ]  Hash.HMAC move to Crypt.MAC #78

**Comment by tsuyoshicho** [comment]
HMAC interface update need

**Comment by tsuyoshicho** [comment]
- [Blowfish \- Wikipedia](https://ja.wikipedia.org/wiki/Blowfish)
- [Twofish \- Wikipedia](https://ja.wikipedia.org/wiki/Twofish)

- [Cryptography \- 256 bit ciphers](https://embeddedsw.net/Cipher_Reference_Home.html)

**Comment by tsuyoshicho** [comment]
# hmac / poly1305 interface integration

## hmac -> mac
mac/calc

## note
- hmac algo -> hash
- poly1305 algo -> encrypt

**Comment by tsuyoshicho** [comment]
- [ ] Random.Xoshiro128StarStar

see
- [xoshiro/xoroshiro generators and the PRNG shootout](http://prng.di.unimi.it/)
- [prng\.di\.unimi\.it/xoshiro128starstar\.c](http://prng.di.unimi.it/xoshiro128starstar.c)

And Random.System default use this.

**Comment by tsuyoshicho** [comment]
本家にないものとして

## Text.
- [ ] JSONのIF
- [ ] JSON5
- [ ] YAML

はどうだろう?

**Comment by tsuyoshicho** [comment]
https://speakerdeck.com/syocy/dhall-haskellfalsexin-tanakiraapuri?slide=13

Dhall reader/writer

**Comment by tsuyoshicho** [comment]
[MurmurHashとは何か \- kenju's blog](https://itiskj.hatenablog.com/entry/2017/09/24/053000) | https://en.wikipedia.org/wiki/MurmurHash

- MurmurHash
- CityHash
- FarmHash
- xxHash
- SipHash

**Comment by tsuyoshicho** [comment]
- bcrypt
- algon2

**Comment by tsuyoshicho** [comment]
- Radix-64

**Comment by tsuyoshicho** [comment]
#165 Radix-64 done

**Comment by tsuyoshicho** [comment]
sort?

https://github.com/scandum/quadsort
